### ISSUE TITLE
Broadcasting with r and c in optimal transport

### ISSUE THREAD

**Issue by quang-anh-nguyen** [anucvml/ddn#20]
Hello I am currently resolving a problem where the cost matrix M of shape (D, D) is somewhat fixed. Meanwhile r and c are batched and of dimension (B, D) and (C, D). Is there a way to adapt so that the layer can compute the OT loss is calculated of shape (B, C). Thank you very much.

**Comment by sgould** [comment]
With the current implementation you would need to replicate along the batch dimension. Something like,

```
M = M.view(1, D, D).repeat(B, 1, 1)
```

The batch dimension for `r` and `c` must match.

**Comment by quang-anh-nguyen** [comment]
Thank you for your clarification.
