### ISSUE TITLE
Computation of fXY extremely slow?

### ISSUE THREAD

**Issue by Parskatt** [anucvml/ddn#6]
# Issue

The forloop involving https://github.com/anucvml/ddn/blob/1240a6990c06e6fad468015afd16571920a3e3d7/ddn/pytorch/node.py#L138-L145 and 

https://github.com/anucvml/ddn/blob/1240a6990c06e6fad468015afd16571920a3e3d7/ddn/pytorch/node.py#L254-L256 is extremely slow.

# Solution?
Simply replacing these with:

```python
gradients = []
for x,size in zip(xs,xs_sizes):
  if x.requires_grad:
    gradient = torch.einsum('byx,by->bx', fXY(x),u).reshape(size)
    gradients.append(gradient)
  else:
    gradients.append(None)
```
```python
fXY = lambda x : self._batch_jacobian(fY, x)
``` 

# Potential Issues with Solution
I am not able to see any issues with the solution. There would need to be some changes to the constrained nodes as well however to accomodate it. Perhaps there is something I'm missing, please let me know if that's the case.

**Comment by dylan-campbell** [comment]
Hi @Parskatt, no I don't think you're missing anything. If I'm remembering that part of the code correctly, there's a memory--speed trade-off here. For a large input x, looping over the input saves a lot of memory. I intend to give the user the option to switch between the two, but that is not yet implemented. This is a good reminder - thank you!

**Comment by Parskatt** [comment]
Ah, I think I understand. Then perhaps it would be better to split the data into chunks if you want to save memory? You could for example have a "chunk_size" parameter which sets the maximum number of elements. This would retain most of the speed while limiting the amount of memory.

**Comment by Parskatt** [comment]
For example pytorch_geometric does that kind of operation for the message passing: https://github.com/rusty1s/pytorch_geometric

**Comment by dylan-campbell** [comment]
Excellent suggestion, thank you! Would you be able to run your problem with the updated code and see if it's fast enough for your usage? It defaults to chunk_size=None, which is no chunking.

**Comment by Parskatt** [comment]
Cool , I'll check it out tomorrow!

**Comment by Parskatt** [comment]
Yes, it works well :) I'll clse this issue.
