### ISSUE TITLE
RuntimeError: cholesky_cuda: For batch 6: U(1,1) is zero, singular U.

### ISSUE THREAD

**Issue by fredzzhang** [anucvml/ddn#8]
# :bug: Bug

Error related to Cholesky factorisation, in `optimal_transport.py` [here](https://github.com/anucvml/ddn/blob/master/ddn/pytorch/optimal_transport.py#L144) at line 144. Adding a small constant `eps` does not solve the problem, even at `eps=1e-1`

## Environment
OS: `Ubuntu 20.04.1 LTS`
PyTorch: `1.7.1`
CUDA Toolkit: `10.2.89`
Python: `3.7.9`

## Reproduction
Data: [data.zip](https://github.com/anucvml/ddn/files/6752463/data.zip)
Code:
```python
import torch

src = 'data'
data = torch.load(src)
r = data['r']
W = data['W']; H = data['H']
P = data['P']; PdivC = data['PdivC']
# A small constant
eps = data['eps']
# Scale the constant if needed
# eps *= 1000
print(eps.max())

block_11 = torch.cholesky(torch.diag_embed(r[:, 1:H]) - torch.einsum("bij,bkj->bik", P[:, 1:H, 0:W], PdivC) + eps)
```

**Comment by sgould** [comment]
Your P in this data contains 'nan' values so I think the problem is earlier in the pipeline, perhaps in obtaining P from the Sinkhorn algorithm.

**Comment by fredzzhang** [comment]
The problem was caused by exponentiating large numbers, resulting in `inf` and `nan` subsequently, which has been fixed in f8a7c59

**Comment by fredzzhang** [comment]
The same problem arises again...I've made sure that there aren't any `nan` values. The data is attached below

[data.pt.zip](https://github.com/anucvml/ddn/files/6762116/data.pt.zip)

**Comment by zwxu064** [comment]
the matrix input to cholesky() is negative definite (the first matrix) which goes against the requirement of positive definite, please try hess_reg_m = torch.eye(H - 1, dtype=r.dtype, device=r.device).view(1, H - 1, H - 1) * hess_reg where hess_reg = 1.0e-8 or slightly larger than 1.0e-8

**Comment by fredzzhang** [comment]
I think the problem is more than numerical precision. I've attached some data that still fail at `1e-1`.

[data.pt.zip](https://github.com/anucvml/ddn/files/6762334/data.pt.zip)

**Comment by zwxu064** [comment]
> I think the problem is more than numerical precision. I've attached some data that still fail at `1e-1`.
> 
> [data.pt.zip](https://github.com/anucvml/ddn/files/6762334/data.pt.zip)

There are some negative real eigen values there. let me try using LU decomposition which does not require PD. Get back to you soon.
